//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Template_4333
{
    using System;
    using System.Collections.Generic;
    
    public partial class reOrder
    {
        public int ID { get; set; }
        public string Code { get; set; }
        public string OrderCode { get; set; }
        public string CreateDate { get; set; }
        public string OrderTime { get; set; }
        public string ClientCode { get; set; }
        public string Services { get; set; }
        public string Status { get; set; }
        public string CloseDate { get; set; }
        public string RentalTime { get; set; }
    }
}
